# Generated by Django 4.1.6 on 2023-02-13 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimenter_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_entree', models.PositiveIntegerField(default=0)),
                ('date_entree', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('telephone', models.CharField(max_length=20)),
                ('base_client', models.CharField(choices=[('Nord', 'Nord'), ('Centre', 'Centre'), ('Sfax', 'Sfax'), ('Sud', 'Sud')], default='nord', max_length=10)),
                ('type_client', models.CharField(choices=[('Pharmacie', 'Pharmacie'), ('Grossiste', 'Grossiste')], default='grossiste', max_length=10)),
                ('taux_remise', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['nom_client'],
            },
        ),
        migrations.CreateModel(
            name='Delegue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_delegue', models.CharField(max_length=200, unique=True)),
                ('base', models.CharField(choices=[('Nord', 'Nord'), ('Centre', 'Centre'), ('Sfax', 'Sfax'), ('Sud', 'Sud')], default='nord', max_length=10)),
            ],
            options={
                'ordering': ['nom_delegue'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantite_stock', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('seuil', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ['nom_produit'],
            },
        ),
        migrations.CreateModel(
            name='VisiteMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('quantite_donne', models.PositiveIntegerField(default=0)),
                ('delegue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitemedicaleDelegue', to='mouvements.delegue')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitemedicaleProduit', to='mouvements.produit')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_BL', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_facture', models.CharField(blank=True, max_length=200, null=True)),
                ('quantite_vendu', models.PositiveIntegerField(default=0)),
                ('date_vente', models.DateField(auto_now_add=True)),
                ('moyen_payement', models.CharField(choices=[('chèque', 'chèque'), ('traite', 'traite'), ('espèces', 'espèces'), ('gratuit', 'gratuit')], default='espèces', max_length=20)),
                ('paye', models.BooleanField(default=False)),
                ('gratuit', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venteclient', to='mouvements.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venteproduit', to='mouvements.produit')),
            ],
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['nom_produit'], name='mouvements__nom_pro_c7e206_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['quantite_stock'], name='mouvements__quantit_af1e67_idx'),
        ),
        migrations.AddIndex(
            model_name='delegue',
            index=models.Index(fields=['nom_delegue'], name='mouvements__nom_del_d6a3b9_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['id'], name='mouvements__id_1e6038_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['nom_client'], name='mouvements__nom_cli_a0be30_idx'),
        ),
        migrations.AddField(
            model_name='alimenter_stock',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alimenterproduit', to='mouvements.produit'),
        ),
    ]
