# Generated by Django 4.1.6 on 2023-02-15 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mouvements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='montant_remise',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='taux_remise_vente',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='RemiseClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_remise', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('date_remise', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remiseclient', to='mouvements.client')),
            ],
            options={
                'ordering': ['-date_remise'],
            },
        ),
    ]
