# Generated by Django 4.1.6 on 2023-02-15 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mouvements', '0002_vente_montant_remise_vente_prix_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remiseclient',
            options={'ordering': ['date_remise']},
        ),
        migrations.RemoveField(
            model_name='vente',
            name='taux_remise_vente',
        ),
    ]
