# Generated by Django 4.1.6 on 2023-02-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouvements', '0003_alter_remiseclient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='date_vente',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
