# Generated by Django 4.1.6 on 2023-02-17 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouvements', '0005_remove_client_telephone_client_fonction1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='taux_remise',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
