# Generated by Django 4.1.6 on 2023-04-22 13:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mouvements', '0013_alter_alimenter_stock_produit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))]),
        ),
        migrations.AlterField(
            model_name='vente',
            name='numero_BL',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
